import { TableClient, odata } from "@azure/data-tables";
import { randomBytes } from "crypto";
import type { Provenance } from "@/lib/insights/types";

/**
 * Recording what readers ask, so the library can answer it next time.
 *
 * The load-bearing column is provenance. A turn answered from general knowledge
 * is a subject the corpus does not cover, and grouped by the article the reader
 * was on it reads as the brief for the next piece. Everything else here exists
 * either to make that column legible or to keep the row inside the retention
 * promise the privacy policy has already made.
 *
 * **What is deliberately absent.** No IP address, no IP hash, no name, no email,
 * no user agent, no referrer. The session id is generated by the client for the
 * life of one page, is not a cookie and is stored nowhere else, so it groups
 * turns into a conversation and identifies nobody. Readers will type
 * confidential things into an assistant however plainly they are asked not to,
 * which is an argument for short retention and a narrow column set, not for
 * capturing less of the useful signal.
 *
 * **Why the partition key is a date.** Both jobs this table has are time ranged:
 * the purge takes everything older than the window and the gap report reads the
 * last few weeks. A date partition turns each into a key range scan instead of a
 * table scan, and a marketing site's write volume never approaches what one
 * partition will take.
 */

const TABLE_NAME = "InsightsConversations";

/**
 * Ninety days.
 *
 * The privacy policy wording that commits to this is written and held in draft PR
 * #90, deliberately unmerged so the live policy does not describe a feature that
 * does not exist yet. It has to go live with the console. Until then this code
 * keeps a promise that has not been published, which is the safe order to do it
 * in but is not the same as the promise being made.
 */
const RETENTION_DAYS = 90;

/** Roughly one write in this many runs the purge. See maybePurge. */
const PURGE_SAMPLE_RATE = 50;

let client: TableClient | null = null;
let tableEnsured = false;

function getClient(): TableClient | null {
  if (client) return client;

  const connectionString = process.env.STORAGE_ACCOUNT_CONNECTION;
  if (!connectionString) {
    console.warn(
      "[insights] STORAGE_ACCOUNT_CONNECTION not set, so conversation capture is off.",
    );
    return null;
  }

  client = TableClient.fromConnectionString(connectionString, TABLE_NAME);
  return client;
}

async function ensureTable(c: TableClient): Promise<void> {
  if (tableEnsured) return;
  try {
    await c.createTable();
    tableEnsured = true;
  } catch (err) {
    const code = (err as { statusCode?: number }).statusCode;
    // 409 is the normal case after the first write of the table's life.
    if (code === 409) {
      tableEnsured = true;
      return;
    }
    // Anything else, and in particular a failure with no status at all, is a
    // transport problem rather than an answer from the service. Leaving the flag
    // down means the next write tries again instead of assuming a table that may
    // not be there.
    console.warn("[insights] createTable(InsightsConversations) failed:", err);
  }
}

/** UTC, because the partition key has to mean the same thing wherever the function runs. */
function utcDate(at: Date): string {
  return at.toISOString().slice(0, 10);
}

export type CapturedTurn = {
  question: string;
  articleSlug: string | null;
  provenance: Provenance;
  citedSlugs: string[];
  /** True when this turn is not the first in its session, which is the continuation signal. */
  continued: boolean;
  askedBack: boolean;
  sessionId: string;
  answerChars: number;
  errorCode: string | null;
};

/** Never throws. A capture failure must not cost the reader their answer. */
export async function recordTurn(turn: CapturedTurn): Promise<void> {
  const c = getClient();
  if (!c) return;

  try {
    await ensureTable(c);

    const now = new Date();
    await c.createEntity({
      partitionKey: utcDate(now),
      // Sortable by write time within the day, with randomness because two turns
      // can land on the same millisecond.
      rowKey: `${now.getTime()}-${randomBytes(4).toString("hex")}`,
      question: turn.question,
      // Table Storage has no useful null, so an empty string is the absent value
      // throughout: no article, no citations, no error.
      articleSlug: turn.articleSlug ?? "",
      provenance: turn.provenance,
      citedSlugs: turn.citedSlugs.join(","),
      continued: turn.continued,
      askedBack: turn.askedBack,
      sessionId: turn.sessionId,
      answerChars: turn.answerChars,
      errorCode: turn.errorCode ?? "",
      createdAt: now.toISOString(),
      // Written false rather than left off, so the purge can find unpurged rows
      // by filter instead of reading every property of every old row back.
      purged: false,
    });
  } catch (err) {
    console.warn("[insights] failed to record the turn:", err);
    return;
  }

  await maybePurge();
}

/**
 * The retention mechanism.
 *
 * There is no scheduler and no cron secret for storage in this repo, and adding
 * one to hold a promise the privacy policy has already made would put the
 * promise behind new infrastructure. Sampling the write path needs none: at one
 * write in fifty the sweep runs several times a day at any traffic worth
 * reporting on, and at no traffic there is nothing arriving to purge. The
 * exported function covers the rest, by hand or from a workflow later.
 *
 * It is awaited because the serverless function can be frozen the moment the
 * response resolves, which is the lesson the telemetry flush already taught, and
 * it swallows everything because a reader's answer must not depend on a sweep.
 */
async function maybePurge(): Promise<void> {
  if (Math.random() >= 1 / PURGE_SAMPLE_RATE) return;
  try {
    const changed = await purgeOldQuestionText();
    if (changed > 0) {
      console.log(`[insights] purged question text from ${changed} row(s).`);
    }
  } catch (err) {
    console.warn("[insights] sampled purge failed:", err);
  }
}

/**
 * The most rows one pass will touch.
 *
 * The purge runs inside a request, sampled, so it cannot be unbounded: the first
 * pass after the window fills could face thousands of rows and the reader would
 * wait for all of them. A bounded pass that runs again on the next sample gets
 * there in a few requests instead of one slow one.
 */
const PURGE_BATCH = 500;

/** Deletes question text older than the retention window, leaving the aggregate row. Returns how many rows it changed. */
export async function purgeOldQuestionText(
  olderThanDays: number = RETENTION_DAYS,
): Promise<number> {
  const c = getClient();
  if (!c) return 0;

  // A date partition key compares lexicographically the way it reads, so this is
  // a range over the keys rather than a scan of the table.
  const cutoff = utcDate(new Date(Date.now() - olderThanDays * 86_400_000));

  const stale = c.listEntities<{ partitionKey: string; rowKey: string }>({
    queryOptions: {
      // Table Storage matches nothing on a property a row does not carry, so a row
      // written without the flag would be invisible here. recordTurn is the only
      // writer and always writes it; anything inserted by hand has to as well.
      filter: odata`PartitionKey lt ${cutoff} and purged eq false`,
      // The question text is the thing being disposed of, so the purge does not
      // read it back to do so.
      select: ["PartitionKey", "RowKey"],
    },
  });

  let changed = 0;
  for await (const row of stale) {
    try {
      // Merge, not replace: the row survives the purge so the counts the gap
      // report is built on survive with it. Only the reader's words go.
      await c.updateEntity(
        { partitionKey: row.partitionKey, rowKey: row.rowKey, question: "", purged: true },
        "Merge",
      );
      changed += 1;
      if (changed >= PURGE_BATCH) break;
    } catch (err) {
      // One row that will not update is not a reason to leave the rest of the
      // window unpurged.
      console.warn(`[insights] purge failed on ${row.partitionKey}/${row.rowKey}:`, err);
    }
  }
  return changed;
}
